import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'hi' | 'fr' | 'ar' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.none': 'None',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.type': 'Type',
    'common.note': 'Note',
    
    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    
    // Navigation
    'nav.home': 'Home',
    'nav.market': 'Market',
    'nav.trade': 'Trade',
    'nav.loan': 'Loan',
    'nav.account': 'Account',
    
    // Admin
    'admin.userManagement': 'User Management',
    'admin.username': 'Username',
    'admin.email': 'Email',
    'admin.balance': 'Balance',
    'admin.loanStatus': 'Loan Status',
    'admin.kyc': 'KYC',
    'admin.registerDate': 'Register Date',
    'admin.modifyBalance': 'Modify Balance',
    'admin.fundDetails': 'Fund Details',
    'admin.freezeAccount': 'Freeze Account',
    'admin.unfreezeAccount': 'Unfreeze Account',
    'admin.userDetails': 'User Details',
    'admin.loginIP': 'Login IP',
    'admin.lastLogin': 'Last Login',
    'admin.kycHistory': 'KYC History',
    'admin.viewDetails': 'View Details',
    'admin.noKYC': 'No KYC Record',
    'admin.kycPhotos': 'KYC Photos',
    'admin.frontImage': 'ID Front',
    'admin.backImage': 'ID Back',
    'admin.selfie': 'Selfie',
    
    // KYC Status
    'kyc.approved': 'Verified',
    'kyc.pending': 'Pending Review',
    'kyc.rejected': 'Rejected',
    'kyc.notSubmitted': 'Not Submitted',
    
    // Account Status
    'status.normal': 'Normal',
    'status.frozen': 'Frozen',
    
    // Loan
    'loan.active': 'Active Loans',
    'loan.pending': 'Pending Approval',
    'loan.noLoan': 'No Loan',
    'loan.owed': 'Owed',
    
    // Footer
    'footer.language': 'Language',
  },
  zh: {
    // Common
    'common.loading': '加载中...',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.close': '关闭',
    'common.submit': '提交',
    'common.success': '成功',
    'common.error': '错误',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.all': '全部',
    'common.none': '无',
    'common.status': '状态',
    'common.actions': '操作',
    'common.date': '日期',
    'common.amount': '金额',
    'common.type': '类型',
    'common.note': '备注',
    
    // Auth
    'auth.login': '登录',
    'auth.logout': '退出登录',
    'auth.register': '注册',
    'auth.email': '邮箱',
    'auth.password': '密码',
    
    // Navigation
    'nav.home': '首页',
    'nav.market': '行情',
    'nav.trade': '交易',
    'nav.loan': '贷款',
    'nav.account': '账户',
    
    // Admin
    'admin.userManagement': '用户管理',
    'admin.username': '用户名',
    'admin.email': '邮箱',
    'admin.balance': '余额',
    'admin.loanStatus': '贷款情况',
    'admin.kyc': '实名认证',
    'admin.registerDate': '注册时间',
    'admin.modifyBalance': '修改余额',
    'admin.fundDetails': '资金明细',
    'admin.freezeAccount': '冻结账户',
    'admin.unfreezeAccount': '解冻账户',
    'admin.userDetails': '用户详情',
    'admin.loginIP': '登录IP',
    'admin.lastLogin': '最后登录',
    'admin.kycHistory': 'KYC历史记录',
    'admin.viewDetails': '查看详情',
    'admin.noKYC': '暂无KYC记录',
    'admin.kycPhotos': 'KYC照片',
    'admin.frontImage': '证件正面',
    'admin.backImage': '证件背面',
    'admin.selfie': '自拍照',
    
    // KYC Status
    'kyc.approved': '已认证',
    'kyc.pending': '待审核',
    'kyc.rejected': '已拒绝',
    'kyc.notSubmitted': '未提交',
    
    // Account Status
    'status.normal': '正常',
    'status.frozen': '已冻结',
    
    // Loan
    'loan.active': '笔进行中',
    'loan.pending': '待审批',
    'loan.noLoan': '无贷款',
    'loan.owed': '欠款',
    
    // Footer
    'footer.language': '语言',
  },
  es: {
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.close': 'Cerrar',
    'common.submit': 'Enviar',
    'common.success': 'Éxito',
    'common.error': 'Error',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.all': 'Todos',
    'common.none': 'Ninguno',
    'common.status': 'Estado',
    'common.actions': 'Acciones',
    'common.date': 'Fecha',
    'common.amount': 'Cantidad',
    'common.type': 'Tipo',
    'common.note': 'Nota',
    'auth.login': 'Iniciar sesión',
    'auth.logout': 'Cerrar sesión',
    'auth.register': 'Registrarse',
    'auth.email': 'Correo',
    'auth.password': 'Contraseña',
    'nav.home': 'Inicio',
    'nav.market': 'Mercado',
    'nav.trade': 'Comercio',
    'nav.loan': 'Préstamo',
    'nav.account': 'Cuenta',
    'admin.userManagement': 'Gestión de usuarios',
    'admin.username': 'Usuario',
    'admin.email': 'Correo',
    'admin.balance': 'Saldo',
    'admin.loanStatus': 'Estado del préstamo',
    'admin.kyc': 'KYC',
    'admin.registerDate': 'Fecha de registro',
    'admin.modifyBalance': 'Modificar saldo',
    'admin.fundDetails': 'Detalles de fondos',
    'admin.freezeAccount': 'Congelar cuenta',
    'admin.unfreezeAccount': 'Descongelar cuenta',
    'admin.userDetails': 'Detalles del usuario',
    'admin.loginIP': 'IP de inicio de sesión',
    'admin.lastLogin': 'Último inicio de sesión',
    'admin.kycHistory': 'Historial KYC',
    'admin.viewDetails': 'Ver detalles',
    'admin.noKYC': 'Sin registro KYC',
    'admin.kycPhotos': 'Fotos KYC',
    'admin.frontImage': 'Frente del ID',
    'admin.backImage': 'Reverso del ID',
    'admin.selfie': 'Selfie',
    'kyc.approved': 'Verificado',
    'kyc.pending': 'Pendiente',
    'kyc.rejected': 'Rechazado',
    'kyc.notSubmitted': 'No enviado',
    'status.normal': 'Normal',
    'status.frozen': 'Congelado',
    'loan.active': 'préstamos activos',
    'loan.pending': 'pendiente de aprobación',
    'loan.noLoan': 'Sin préstamo',
    'loan.owed': 'Adeudado',
    'footer.language': 'Idioma',
  },
  hi: {
    'common.loading': 'लोड हो रहा है...',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.confirm': 'पुष्टि करें',
    'common.close': 'बंद करें',
    'common.submit': 'जमा करें',
    'common.success': 'सफलता',
    'common.error': 'त्रुटि',
    'common.search': 'खोजें',
    'common.filter': 'फ़िल्टर',
    'common.all': 'सभी',
    'common.none': 'कोई नहीं',
    'common.status': 'स्थिति',
    'common.actions': 'क्रियाएं',
    'common.date': 'तारीख',
    'common.amount': 'राशि',
    'common.type': 'प्रकार',
    'common.note': 'नोट',
    'auth.login': 'लॉगिन',
    'auth.logout': 'लॉगआउट',
    'auth.register': 'पंजीकरण',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'nav.home': 'होम',
    'nav.market': 'बाज़ार',
    'nav.trade': 'व्यापार',
    'nav.loan': 'ऋण',
    'nav.account': 'खाता',
    'admin.userManagement': 'उपयोगकर्ता प्रबंधन',
    'admin.username': 'उपयोगकर्ता नाम',
    'admin.email': 'ईमेल',
    'admin.balance': 'शेष राशि',
    'admin.loanStatus': 'ऋण स्थिति',
    'admin.kyc': 'KYC',
    'admin.registerDate': 'पंजीकरण तिथि',
    'admin.modifyBalance': 'शेष संशोधित करें',
    'admin.fundDetails': 'फंड विवरण',
    'admin.freezeAccount': 'खाता फ्रीज करें',
    'admin.unfreezeAccount': 'खाता अनफ्रीज करें',
    'admin.userDetails': 'उपयोगकर्ता विवरण',
    'admin.loginIP': 'लॉगिन IP',
    'admin.lastLogin': 'अंतिम लॉगिन',
    'admin.kycHistory': 'KYC इतिहास',
    'admin.viewDetails': 'विवरण देखें',
    'admin.noKYC': 'कोई KYC रिकॉर्ड नहीं',
    'admin.kycPhotos': 'KYC फोटो',
    'admin.frontImage': 'ID सामने',
    'admin.backImage': 'ID पीछे',
    'admin.selfie': 'सेल्फी',
    'kyc.approved': 'सत्यापित',
    'kyc.pending': 'लंबित',
    'kyc.rejected': 'अस्वीकृत',
    'kyc.notSubmitted': 'जमा नहीं',
    'status.normal': 'सामान्य',
    'status.frozen': 'फ्रोजन',
    'loan.active': 'सक्रिय ऋण',
    'loan.pending': 'अनुमोदन लंबित',
    'loan.noLoan': 'कोई ऋण नहीं',
    'loan.owed': 'बकाया',
    'footer.language': 'भाषा',
  },
  fr: {
    'common.loading': 'Chargement...',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.close': 'Fermer',
    'common.submit': 'Soumettre',
    'common.success': 'Succès',
    'common.error': 'Erreur',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.all': 'Tous',
    'common.none': 'Aucun',
    'common.status': 'Statut',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.amount': 'Montant',
    'common.type': 'Type',
    'common.note': 'Note',
    'auth.login': 'Connexion',
    'auth.logout': 'Déconnexion',
    'auth.register': "S'inscrire",
    'auth.email': 'E-mail',
    'auth.password': 'Mot de passe',
    'nav.home': 'Accueil',
    'nav.market': 'Marché',
    'nav.trade': 'Commerce',
    'nav.loan': 'Prêt',
    'nav.account': 'Compte',
    'admin.userManagement': 'Gestion des utilisateurs',
    'admin.username': "Nom d'utilisateur",
    'admin.email': 'E-mail',
    'admin.balance': 'Solde',
    'admin.loanStatus': 'Statut du prêt',
    'admin.kyc': 'KYC',
    'admin.registerDate': "Date d'inscription",
    'admin.modifyBalance': 'Modifier le solde',
    'admin.fundDetails': 'Détails des fonds',
    'admin.freezeAccount': 'Geler le compte',
    'admin.unfreezeAccount': 'Dégeler le compte',
    'admin.userDetails': "Détails de l'utilisateur",
    'admin.loginIP': 'IP de connexion',
    'admin.lastLogin': 'Dernière connexion',
    'admin.kycHistory': 'Historique KYC',
    'admin.viewDetails': 'Voir les détails',
    'admin.noKYC': 'Aucun enregistrement KYC',
    'admin.kycPhotos': 'Photos KYC',
    'admin.frontImage': "Recto de l'ID",
    'admin.backImage': "Verso de l'ID",
    'admin.selfie': 'Selfie',
    'kyc.approved': 'Vérifié',
    'kyc.pending': 'En attente',
    'kyc.rejected': 'Rejeté',
    'kyc.notSubmitted': 'Non soumis',
    'status.normal': 'Normal',
    'status.frozen': 'Gelé',
    'loan.active': 'prêts actifs',
    'loan.pending': "en attente d'approbation",
    'loan.noLoan': 'Pas de prêt',
    'loan.owed': 'Dû',
    'footer.language': 'Langue',
  },
  ar: {
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.close': 'إغلاق',
    'common.submit': 'إرسال',
    'common.success': 'نجاح',
    'common.error': 'خطأ',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.all': 'الكل',
    'common.none': 'لا شيء',
    'common.status': 'الحالة',
    'common.actions': 'الإجراءات',
    'common.date': 'التاريخ',
    'common.amount': 'المبلغ',
    'common.type': 'النوع',
    'common.note': 'ملاحظة',
    'auth.login': 'تسجيل الدخول',
    'auth.logout': 'تسجيل الخروج',
    'auth.register': 'التسجيل',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'nav.home': 'الرئيسية',
    'nav.market': 'السوق',
    'nav.trade': 'التداول',
    'nav.loan': 'القرض',
    'nav.account': 'الحساب',
    'admin.userManagement': 'إدارة المستخدمين',
    'admin.username': 'اسم المستخدم',
    'admin.email': 'البريد الإلكتروني',
    'admin.balance': 'الرصيد',
    'admin.loanStatus': 'حالة القرض',
    'admin.kyc': 'التحقق من الهوية',
    'admin.registerDate': 'تاريخ التسجيل',
    'admin.modifyBalance': 'تعديل الرصيد',
    'admin.fundDetails': 'تفاصيل الأموال',
    'admin.freezeAccount': 'تجميد الحساب',
    'admin.unfreezeAccount': 'إلغاء تجميد الحساب',
    'admin.userDetails': 'تفاصيل المستخدم',
    'admin.loginIP': 'عنوان IP لتسجيل الدخول',
    'admin.lastLogin': 'آخر تسجيل دخول',
    'admin.kycHistory': 'سجل التحقق',
    'admin.viewDetails': 'عرض التفاصيل',
    'admin.noKYC': 'لا يوجد سجل تحقق',
    'admin.kycPhotos': 'صور التحقق',
    'admin.frontImage': 'صورة الهوية الأمامية',
    'admin.backImage': 'صورة الهوية الخلفية',
    'admin.selfie': 'صورة سيلفي',
    'kyc.approved': 'تم التحقق',
    'kyc.pending': 'قيد الانتظار',
    'kyc.rejected': 'مرفوض',
    'kyc.notSubmitted': 'لم يتم الإرسال',
    'status.normal': 'عادي',
    'status.frozen': 'مجمد',
    'loan.active': 'قروض نشطة',
    'loan.pending': 'في انتظار الموافقة',
    'loan.noLoan': 'لا يوجد قرض',
    'loan.owed': 'مستحق',
    'footer.language': 'اللغة',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('preferred-language');
    return (stored as Language) || 'zh';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('preferred-language', lang);
    // Set document direction for RTL languages
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  };

  useEffect(() => {
    // Set initial direction
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
