import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'hi' | 'fr' | 'ar' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.none': 'None',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.type': 'Type',
    'common.note': 'Note',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.add': 'Add',
    'common.update': 'Update',
    
    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.register': 'Register',
    'auth.signUp': 'Sign up',
    'auth.signIn': 'Sign In',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.username': 'Username',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.createAccount': 'Create Account',
    'auth.enterCredentials': 'Enter your credentials to access your account',
    'auth.fillDetails': 'Fill in your details to get started',
    'auth.loggingIn': 'Logging in...',
    'auth.registering': 'Registering...',
    'auth.backToHome': '← Back to Home',
    'auth.welcomeBack': 'Welcome Back to MetaMask Trade',
    'auth.startJourney': 'Start Your Investment Journey',
    'auth.accessPortfolio': 'Access your portfolio and continue trading with the most secure platform.',
    'auth.completeRegistration': 'Complete your registration and unlock the gateway to exciting investment opportunities.',
    'auth.connectWallet': 'Connect Wallet',
    'auth.openMetaMask': 'Open in MetaMask',
    'auth.orContinueEmail': 'Or continue with email',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.chooseUsername': 'Choose a username',
    'auth.createPassword': 'Create a password (min 6 chars)',
    'auth.confirmYourPassword': 'Confirm your password',
    
    // Navigation
    'nav.home': 'Home',
    'nav.market': 'Market',
    'nav.trade': 'Trade',
    'nav.smartTrading': 'Smart Trading',
    'nav.loan': 'Loan',
    'nav.account': 'Account',
    'nav.admin': 'Admin',
    'nav.adminPanel': 'Admin Panel',
    'nav.customerService': 'Customer Service',
    
    // Hero Section
    'hero.title': 'Buy, trade, and hold 350+ cryptocurrencies on MetaMask Trade',
    'hero.appStore': 'App Store',
    'hero.application': 'Application',
    'hero.appDescription': 'Mobile banking that throws out the role book and gives you a precision tool for managing your finances.',
    'hero.cryptoDeposit': 'Crypto deposit',
    'hero.cryptoDescription': 'By using cryptocurrency for deposit, an additional layer of security is obtained.',
    
    // Features
    'feature.bankSecurity': 'Bank-Level Security',
    'feature.bankSecurityDesc': '256-bit encryption for all transactions',
    'feature.realTimeTrading': 'Real-Time Trading',
    'feature.realTimeTradingDesc': 'Trade 350+ cryptocurrencies instantly',
    'feature.selfCustody': 'Self-Custody',
    'feature.selfCustodyDesc': 'You control your private keys',
    'feature.secureAndTrusted': 'Secure & Trusted',
    
    // Footer
    'footer.language': 'Language',
    'footer.description': 'The world\'s leading cryptocurrency exchange platform. Trade securely with the lowest fees and fastest execution.',
    'footer.products': 'Products',
    'footer.spotTrading': 'Spot Trading',
    'footer.marginTrading': 'Margin Trading',
    'footer.derivatives': 'Derivatives',
    'footer.loans': 'Loans',
    'footer.services': 'Services',
    'footer.copyTrading': 'Copy Trading',
    'footer.api': 'API',
    'footer.mobileApp': 'Mobile App',
    'footer.support': 'Support',
    'footer.helpCenter': 'Help Center',
    'footer.contactUs': 'Contact Us',
    'footer.faq': 'FAQ',
    'footer.fees': 'Fees',
    'footer.legal': 'Legal',
    'footer.allRightsReserved': 'All rights reserved.',
    
    // Admin
    'admin.userManagement': 'User Management',
    'admin.username': 'Username',
    'admin.email': 'Email',
    'admin.balance': 'Balance',
    'admin.loanStatus': 'Loan Status',
    'admin.kyc': 'KYC',
    'admin.registerDate': 'Register Date',
    'admin.modifyBalance': 'Modify Balance',
    'admin.fundDetails': 'Fund Details',
    'admin.freezeAccount': 'Freeze Account',
    'admin.unfreezeAccount': 'Unfreeze Account',
    'admin.userDetails': 'User Details',
    'admin.loginIP': 'Login IP',
    'admin.lastLogin': 'Last Login',
    'admin.kycHistory': 'KYC History',
    'admin.viewDetails': 'View Details',
    'admin.noKYC': 'No KYC Record',
    'admin.kycPhotos': 'KYC Photos',
    'admin.frontImage': 'ID Front',
    'admin.backImage': 'ID Back',
    'admin.selfie': 'Selfie',
    'admin.changePassword': 'Change Password',
    'admin.newPassword': 'New Password',
    'admin.confirmNewPassword': 'Confirm New Password',
    'admin.passwordMinLength': 'Password must be at least 6 characters',
    'admin.passwordMismatch': 'Passwords do not match',
    
    // KYC Status
    'kyc.approved': 'Verified',
    'kyc.pending': 'Pending Review',
    'kyc.rejected': 'Rejected',
    'kyc.notSubmitted': 'Not Submitted',
    
    // Account Status
    'status.normal': 'Normal',
    'status.frozen': 'Frozen',
    
    // Loan
    'loan.active': 'Active Loans',
    'loan.pending': 'Pending Approval',
    'loan.noLoan': 'No Loan',
    'loan.owed': 'Owed',
    
    // Account Page
    'account.myAssets': 'My Assets',
    'account.totalBalance': 'Total Balance',
    'account.deposit': 'Deposit',
    'account.withdraw': 'Withdraw',
    'account.transfer': 'Transfer',
    'account.tradeHistory': 'Trade History',
    'account.settings': 'Settings',
    'account.security': 'Security',
    'account.verification': 'Verification',
  },
  zh: {
    // Common
    'common.loading': '加载中...',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.close': '关闭',
    'common.submit': '提交',
    'common.success': '成功',
    'common.error': '错误',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.all': '全部',
    'common.none': '无',
    'common.status': '状态',
    'common.actions': '操作',
    'common.date': '日期',
    'common.amount': '金额',
    'common.type': '类型',
    'common.note': '备注',
    'common.back': '返回',
    'common.next': '下一步',
    'common.previous': '上一步',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.view': '查看',
    'common.add': '添加',
    'common.update': '更新',
    
    // Auth
    'auth.login': '登录',
    'auth.logout': '退出登录',
    'auth.register': '注册',
    'auth.signUp': '注册',
    'auth.signIn': '登录',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.username': '用户名',
    'auth.forgotPassword': '忘记密码？',
    'auth.noAccount': '还没有账户？',
    'auth.hasAccount': '已有账户？',
    'auth.createAccount': '创建账户',
    'auth.enterCredentials': '输入您的凭据以访问您的账户',
    'auth.fillDetails': '填写您的详细信息以开始',
    'auth.loggingIn': '登录中...',
    'auth.registering': '注册中...',
    'auth.backToHome': '← 返回首页',
    'auth.welcomeBack': '欢迎回到 MetaMask Trade',
    'auth.startJourney': '开启您的投资之旅',
    'auth.accessPortfolio': '访问您的投资组合，使用最安全的平台继续交易。',
    'auth.completeRegistration': '完成注册，开启激动人心的投资机会。',
    'auth.connectWallet': '连接钱包',
    'auth.openMetaMask': '在 MetaMask 中打开',
    'auth.orContinueEmail': '或使用邮箱继续',
    'auth.enterEmail': '输入您的邮箱',
    'auth.enterPassword': '输入您的密码',
    'auth.chooseUsername': '选择用户名',
    'auth.createPassword': '创建密码（至少6位）',
    'auth.confirmYourPassword': '确认您的密码',
    
    // Navigation
    'nav.home': '首页',
    'nav.market': '行情',
    'nav.trade': '交易',
    'nav.smartTrading': '智能交易',
    'nav.loan': '贷款',
    'nav.account': '账户',
    'nav.admin': '管理',
    'nav.adminPanel': '管理面板',
    'nav.customerService': '客服',
    
    // Hero Section
    'hero.title': '在 MetaMask Trade 购买、交易和持有 350+ 种加密货币',
    'hero.appStore': 'App Store',
    'hero.application': '应用程序',
    'hero.appDescription': '移动银行打破常规，为您提供精确的财务管理工具。',
    'hero.cryptoDeposit': '加密货币充值',
    'hero.cryptoDescription': '使用加密货币充值，获得额外的安全保障。',
    
    // Features
    'feature.bankSecurity': '银行级安全',
    'feature.bankSecurityDesc': '所有交易采用256位加密',
    'feature.realTimeTrading': '实时交易',
    'feature.realTimeTradingDesc': '即时交易350+种加密货币',
    'feature.selfCustody': '自托管',
    'feature.selfCustodyDesc': '您控制自己的私钥',
    'feature.secureAndTrusted': '安全可信',
    
    // Footer
    'footer.language': '语言',
    'footer.description': '全球领先的加密货币交易平台。以最低的费用和最快的执行速度安全交易。',
    'footer.products': '产品',
    'footer.spotTrading': '现货交易',
    'footer.marginTrading': '保证金交易',
    'footer.derivatives': '衍生品',
    'footer.loans': '贷款',
    'footer.services': '服务',
    'footer.copyTrading': '跟单交易',
    'footer.api': 'API',
    'footer.mobileApp': '移动应用',
    'footer.support': '支持',
    'footer.helpCenter': '帮助中心',
    'footer.contactUs': '联系我们',
    'footer.faq': '常见问题',
    'footer.fees': '费率',
    'footer.legal': '法律',
    'footer.allRightsReserved': '版权所有。',
    
    // Admin
    'admin.userManagement': '用户管理',
    'admin.username': '用户名',
    'admin.email': '邮箱',
    'admin.balance': '余额',
    'admin.loanStatus': '贷款情况',
    'admin.kyc': '实名认证',
    'admin.registerDate': '注册时间',
    'admin.modifyBalance': '修改余额',
    'admin.fundDetails': '资金明细',
    'admin.freezeAccount': '冻结账户',
    'admin.unfreezeAccount': '解冻账户',
    'admin.userDetails': '用户详情',
    'admin.loginIP': '登录IP',
    'admin.lastLogin': '最后登录',
    'admin.kycHistory': 'KYC历史记录',
    'admin.viewDetails': '查看详情',
    'admin.noKYC': '暂无KYC记录',
    'admin.kycPhotos': 'KYC照片',
    'admin.frontImage': '证件正面',
    'admin.backImage': '证件背面',
    'admin.selfie': '自拍照',
    'admin.changePassword': '修改密码',
    'admin.newPassword': '新密码',
    'admin.confirmNewPassword': '确认新密码',
    'admin.passwordMinLength': '密码至少需要6个字符',
    'admin.passwordMismatch': '两次密码不一致',
    
    // KYC Status
    'kyc.approved': '已认证',
    'kyc.pending': '待审核',
    'kyc.rejected': '已拒绝',
    'kyc.notSubmitted': '未提交',
    
    // Account Status
    'status.normal': '正常',
    'status.frozen': '已冻结',
    
    // Loan
    'loan.active': '笔进行中',
    'loan.pending': '待审批',
    'loan.noLoan': '无贷款',
    'loan.owed': '欠款',
    
    // Account Page
    'account.myAssets': '我的资产',
    'account.totalBalance': '总余额',
    'account.deposit': '充值',
    'account.withdraw': '提现',
    'account.transfer': '转账',
    'account.tradeHistory': '交易历史',
    'account.settings': '设置',
    'account.security': '安全',
    'account.verification': '身份验证',
  },
  es: {
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.close': 'Cerrar',
    'common.submit': 'Enviar',
    'common.success': 'Éxito',
    'common.error': 'Error',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.all': 'Todos',
    'common.none': 'Ninguno',
    'common.status': 'Estado',
    'common.actions': 'Acciones',
    'common.date': 'Fecha',
    'common.amount': 'Cantidad',
    'common.type': 'Tipo',
    'common.note': 'Nota',
    'common.back': 'Volver',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.add': 'Añadir',
    'common.update': 'Actualizar',
    'auth.login': 'Iniciar sesión',
    'auth.logout': 'Cerrar sesión',
    'auth.register': 'Registrarse',
    'auth.signUp': 'Registrarse',
    'auth.signIn': 'Iniciar sesión',
    'auth.email': 'Correo',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar contraseña',
    'auth.username': 'Usuario',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',
    'auth.createAccount': 'Crear cuenta',
    'auth.enterCredentials': 'Ingresa tus credenciales para acceder',
    'auth.fillDetails': 'Completa tus datos para comenzar',
    'auth.loggingIn': 'Iniciando sesión...',
    'auth.registering': 'Registrando...',
    'auth.backToHome': '← Volver al inicio',
    'auth.welcomeBack': 'Bienvenido a MetaMask Trade',
    'auth.startJourney': 'Comienza tu viaje de inversión',
    'auth.connectWallet': 'Conectar billetera',
    'auth.openMetaMask': 'Abrir en MetaMask',
    'auth.orContinueEmail': 'O continúa con correo',
    'auth.enterEmail': 'Ingresa tu correo',
    'auth.enterPassword': 'Ingresa tu contraseña',
    'auth.chooseUsername': 'Elige un nombre de usuario',
    'auth.createPassword': 'Crea una contraseña (mín 6 caracteres)',
    'auth.confirmYourPassword': 'Confirma tu contraseña',
    'nav.home': 'Inicio',
    'nav.market': 'Mercado',
    'nav.trade': 'Comercio',
    'nav.smartTrading': 'Trading Inteligente',
    'nav.loan': 'Préstamo',
    'nav.account': 'Cuenta',
    'nav.admin': 'Admin',
    'nav.adminPanel': 'Panel de Admin',
    'nav.customerService': 'Servicio al cliente',
    'hero.title': 'Compra, intercambia y mantén más de 350 criptomonedas en MetaMask Trade',
    'hero.appStore': 'App Store',
    'hero.application': 'Aplicación',
    'hero.appDescription': 'Banca móvil que rompe las reglas y te da una herramienta precisa para gestionar tus finanzas.',
    'hero.cryptoDeposit': 'Depósito cripto',
    'hero.cryptoDescription': 'Al usar criptomonedas para depósitos, se obtiene una capa adicional de seguridad.',
    'feature.bankSecurity': 'Seguridad bancaria',
    'feature.bankSecurityDesc': 'Encriptación de 256 bits para todas las transacciones',
    'feature.realTimeTrading': 'Trading en tiempo real',
    'feature.realTimeTradingDesc': 'Intercambia más de 350 criptomonedas al instante',
    'feature.selfCustody': 'Auto-custodia',
    'feature.selfCustodyDesc': 'Tú controlas tus claves privadas',
    'feature.secureAndTrusted': 'Seguro y confiable',
    'footer.language': 'Idioma',
    'footer.description': 'La plataforma de intercambio de criptomonedas líder en el mundo.',
    'footer.products': 'Productos',
    'footer.spotTrading': 'Trading Spot',
    'footer.marginTrading': 'Trading con margen',
    'footer.derivatives': 'Derivados',
    'footer.loans': 'Préstamos',
    'footer.services': 'Servicios',
    'footer.copyTrading': 'Copy Trading',
    'footer.api': 'API',
    'footer.mobileApp': 'App Móvil',
    'footer.support': 'Soporte',
    'footer.helpCenter': 'Centro de ayuda',
    'footer.contactUs': 'Contáctanos',
    'footer.faq': 'FAQ',
    'footer.fees': 'Tarifas',
    'footer.legal': 'Legal',
    'footer.allRightsReserved': 'Todos los derechos reservados.',
    'admin.userManagement': 'Gestión de usuarios',
    'admin.username': 'Usuario',
    'admin.email': 'Correo',
    'admin.balance': 'Saldo',
    'admin.loanStatus': 'Estado del préstamo',
    'admin.kyc': 'KYC',
    'admin.registerDate': 'Fecha de registro',
    'admin.modifyBalance': 'Modificar saldo',
    'admin.fundDetails': 'Detalles de fondos',
    'admin.freezeAccount': 'Congelar cuenta',
    'admin.unfreezeAccount': 'Descongelar cuenta',
    'admin.userDetails': 'Detalles del usuario',
    'admin.loginIP': 'IP de inicio de sesión',
    'admin.lastLogin': 'Último inicio de sesión',
    'admin.kycHistory': 'Historial KYC',
    'admin.viewDetails': 'Ver detalles',
    'admin.noKYC': 'Sin registro KYC',
    'admin.kycPhotos': 'Fotos KYC',
    'admin.frontImage': 'Frente del ID',
    'admin.backImage': 'Reverso del ID',
    'admin.selfie': 'Selfie',
    'admin.changePassword': 'Cambiar contraseña',
    'admin.newPassword': 'Nueva contraseña',
    'admin.confirmNewPassword': 'Confirmar nueva contraseña',
    'admin.passwordMinLength': 'La contraseña debe tener al menos 6 caracteres',
    'admin.passwordMismatch': 'Las contraseñas no coinciden',
    'kyc.approved': 'Verificado',
    'kyc.pending': 'Pendiente',
    'kyc.rejected': 'Rechazado',
    'kyc.notSubmitted': 'No enviado',
    'status.normal': 'Normal',
    'status.frozen': 'Congelado',
    'loan.active': 'préstamos activos',
    'loan.pending': 'pendiente de aprobación',
    'loan.noLoan': 'Sin préstamo',
    'loan.owed': 'Adeudado',
    'account.myAssets': 'Mis activos',
    'account.totalBalance': 'Balance total',
    'account.deposit': 'Depositar',
    'account.withdraw': 'Retirar',
    'account.transfer': 'Transferir',
    'account.tradeHistory': 'Historial de trades',
    'account.settings': 'Configuración',
    'account.security': 'Seguridad',
    'account.verification': 'Verificación',
  },
  hi: {
    'common.loading': 'लोड हो रहा है...',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.confirm': 'पुष्टि करें',
    'common.close': 'बंद करें',
    'common.submit': 'जमा करें',
    'common.success': 'सफलता',
    'common.error': 'त्रुटि',
    'common.search': 'खोजें',
    'common.filter': 'फ़िल्टर',
    'common.all': 'सभी',
    'common.none': 'कोई नहीं',
    'common.status': 'स्थिति',
    'common.actions': 'क्रियाएं',
    'common.date': 'तारीख',
    'common.amount': 'राशि',
    'common.type': 'प्रकार',
    'common.note': 'नोट',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.previous': 'पिछला',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.view': 'देखें',
    'common.add': 'जोड़ें',
    'common.update': 'अपडेट करें',
    'auth.login': 'लॉगिन',
    'auth.logout': 'लॉगआउट',
    'auth.register': 'पंजीकरण',
    'auth.signUp': 'साइन अप',
    'auth.signIn': 'साइन इन',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'auth.username': 'उपयोगकर्ता नाम',
    'auth.noAccount': 'कोई खाता नहीं है?',
    'auth.hasAccount': 'पहले से खाता है?',
    'auth.createAccount': 'खाता बनाएं',
    'auth.connectWallet': 'वॉलेट कनेक्ट करें',
    'auth.openMetaMask': 'MetaMask में खोलें',
    'auth.orContinueEmail': 'या ईमेल से जारी रखें',
    'nav.home': 'होम',
    'nav.market': 'बाज़ार',
    'nav.trade': 'व्यापार',
    'nav.smartTrading': 'स्मार्ट ट्रेडिंग',
    'nav.loan': 'ऋण',
    'nav.account': 'खाता',
    'nav.admin': 'एडमिन',
    'nav.customerService': 'ग्राहक सेवा',
    'hero.title': 'MetaMask Trade पर 350+ क्रिप्टोकरेंसी खरीदें, ट्रेड करें और होल्ड करें',
    'footer.language': 'भाषा',
    'admin.userManagement': 'उपयोगकर्ता प्रबंधन',
    'admin.username': 'उपयोगकर्ता नाम',
    'admin.email': 'ईमेल',
    'admin.balance': 'शेष राशि',
    'admin.loanStatus': 'ऋण स्थिति',
    'admin.kyc': 'KYC',
    'admin.registerDate': 'पंजीकरण तिथि',
    'admin.modifyBalance': 'शेष संशोधित करें',
    'admin.fundDetails': 'फंड विवरण',
    'admin.freezeAccount': 'खाता फ्रीज करें',
    'admin.unfreezeAccount': 'खाता अनफ्रीज करें',
    'admin.userDetails': 'उपयोगकर्ता विवरण',
    'admin.loginIP': 'लॉगिन IP',
    'admin.lastLogin': 'अंतिम लॉगिन',
    'admin.kycHistory': 'KYC इतिहास',
    'admin.viewDetails': 'विवरण देखें',
    'admin.noKYC': 'कोई KYC रिकॉर्ड नहीं',
    'admin.changePassword': 'पासवर्ड बदलें',
    'admin.newPassword': 'नया पासवर्ड',
    'admin.confirmNewPassword': 'नए पासवर्ड की पुष्टि करें',
    'admin.passwordMinLength': 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
    'admin.passwordMismatch': 'पासवर्ड मेल नहीं खाते',
    'kyc.approved': 'सत्यापित',
    'kyc.pending': 'लंबित',
    'kyc.rejected': 'अस्वीकृत',
    'kyc.notSubmitted': 'जमा नहीं',
    'status.normal': 'सामान्य',
    'status.frozen': 'फ्रोजन',
    'loan.active': 'सक्रिय ऋण',
    'loan.pending': 'अनुमोदन लंबित',
    'loan.noLoan': 'कोई ऋण नहीं',
    'loan.owed': 'बकाया',
  },
  fr: {
    'common.loading': 'Chargement...',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.close': 'Fermer',
    'common.submit': 'Soumettre',
    'common.success': 'Succès',
    'common.error': 'Erreur',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.all': 'Tous',
    'common.none': 'Aucun',
    'common.status': 'Statut',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.amount': 'Montant',
    'common.type': 'Type',
    'common.note': 'Note',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.add': 'Ajouter',
    'common.update': 'Mettre à jour',
    'auth.login': 'Connexion',
    'auth.logout': 'Déconnexion',
    'auth.register': "S'inscrire",
    'auth.signUp': "S'inscrire",
    'auth.signIn': 'Se connecter',
    'auth.email': 'E-mail',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.username': "Nom d'utilisateur",
    'auth.noAccount': "Pas de compte?",
    'auth.hasAccount': 'Déjà un compte?',
    'auth.createAccount': 'Créer un compte',
    'auth.connectWallet': 'Connecter le portefeuille',
    'auth.openMetaMask': 'Ouvrir dans MetaMask',
    'auth.orContinueEmail': 'Ou continuer avec email',
    'nav.home': 'Accueil',
    'nav.market': 'Marché',
    'nav.trade': 'Commerce',
    'nav.smartTrading': 'Trading Intelligent',
    'nav.loan': 'Prêt',
    'nav.account': 'Compte',
    'nav.admin': 'Admin',
    'nav.customerService': 'Service client',
    'hero.title': 'Achetez, échangez et conservez plus de 350 cryptomonnaies sur MetaMask Trade',
    'footer.language': 'Langue',
    'admin.userManagement': 'Gestion des utilisateurs',
    'admin.username': "Nom d'utilisateur",
    'admin.email': 'E-mail',
    'admin.balance': 'Solde',
    'admin.loanStatus': 'Statut du prêt',
    'admin.kyc': 'KYC',
    'admin.registerDate': "Date d'inscription",
    'admin.modifyBalance': 'Modifier le solde',
    'admin.fundDetails': 'Détails des fonds',
    'admin.freezeAccount': 'Geler le compte',
    'admin.unfreezeAccount': 'Dégeler le compte',
    'admin.userDetails': "Détails de l'utilisateur",
    'admin.loginIP': 'IP de connexion',
    'admin.lastLogin': 'Dernière connexion',
    'admin.kycHistory': 'Historique KYC',
    'admin.viewDetails': 'Voir les détails',
    'admin.noKYC': 'Aucun enregistrement KYC',
    'admin.changePassword': 'Changer le mot de passe',
    'admin.newPassword': 'Nouveau mot de passe',
    'admin.confirmNewPassword': 'Confirmer le nouveau mot de passe',
    'admin.passwordMinLength': 'Le mot de passe doit comporter au moins 6 caractères',
    'admin.passwordMismatch': 'Les mots de passe ne correspondent pas',
    'kyc.approved': 'Vérifié',
    'kyc.pending': 'En attente',
    'kyc.rejected': 'Rejeté',
    'kyc.notSubmitted': 'Non soumis',
    'status.normal': 'Normal',
    'status.frozen': 'Gelé',
    'loan.active': 'prêts actifs',
    'loan.pending': "en attente d'approbation",
    'loan.noLoan': 'Pas de prêt',
    'loan.owed': 'Dû',
  },
  ar: {
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.close': 'إغلاق',
    'common.submit': 'إرسال',
    'common.success': 'نجاح',
    'common.error': 'خطأ',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.all': 'الكل',
    'common.none': 'لا شيء',
    'common.status': 'الحالة',
    'common.actions': 'الإجراءات',
    'common.date': 'التاريخ',
    'common.amount': 'المبلغ',
    'common.type': 'النوع',
    'common.note': 'ملاحظة',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.view': 'عرض',
    'common.add': 'إضافة',
    'common.update': 'تحديث',
    'auth.login': 'تسجيل الدخول',
    'auth.logout': 'تسجيل الخروج',
    'auth.register': 'التسجيل',
    'auth.signUp': 'التسجيل',
    'auth.signIn': 'تسجيل الدخول',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.username': 'اسم المستخدم',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.hasAccount': 'لديك حساب بالفعل؟',
    'auth.createAccount': 'إنشاء حساب',
    'auth.connectWallet': 'ربط المحفظة',
    'auth.openMetaMask': 'فتح في MetaMask',
    'auth.orContinueEmail': 'أو استمر بالبريد الإلكتروني',
    'nav.home': 'الرئيسية',
    'nav.market': 'السوق',
    'nav.trade': 'التداول',
    'nav.smartTrading': 'التداول الذكي',
    'nav.loan': 'القرض',
    'nav.account': 'الحساب',
    'nav.admin': 'المسؤول',
    'nav.customerService': 'خدمة العملاء',
    'hero.title': 'اشترِ وتداول واحتفظ بأكثر من 350 عملة مشفرة على MetaMask Trade',
    'footer.language': 'اللغة',
    'admin.userManagement': 'إدارة المستخدمين',
    'admin.username': 'اسم المستخدم',
    'admin.email': 'البريد الإلكتروني',
    'admin.balance': 'الرصيد',
    'admin.loanStatus': 'حالة القرض',
    'admin.kyc': 'التحقق من الهوية',
    'admin.registerDate': 'تاريخ التسجيل',
    'admin.modifyBalance': 'تعديل الرصيد',
    'admin.fundDetails': 'تفاصيل الأموال',
    'admin.freezeAccount': 'تجميد الحساب',
    'admin.unfreezeAccount': 'إلغاء تجميد الحساب',
    'admin.userDetails': 'تفاصيل المستخدم',
    'admin.loginIP': 'عنوان IP لتسجيل الدخول',
    'admin.lastLogin': 'آخر تسجيل دخول',
    'admin.kycHistory': 'سجل التحقق',
    'admin.viewDetails': 'عرض التفاصيل',
    'admin.noKYC': 'لا يوجد سجل تحقق',
    'admin.changePassword': 'تغيير كلمة المرور',
    'admin.newPassword': 'كلمة المرور الجديدة',
    'admin.confirmNewPassword': 'تأكيد كلمة المرور الجديدة',
    'admin.passwordMinLength': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
    'admin.passwordMismatch': 'كلمات المرور غير متطابقة',
    'kyc.approved': 'تم التحقق',
    'kyc.pending': 'قيد الانتظار',
    'kyc.rejected': 'مرفوض',
    'kyc.notSubmitted': 'لم يتم الإرسال',
    'status.normal': 'عادي',
    'status.frozen': 'مجمد',
    'loan.active': 'قروض نشطة',
    'loan.pending': 'في انتظار الموافقة',
    'loan.noLoan': 'لا يوجد قرض',
    'loan.owed': 'مستحق',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('preferred-language');
    return (stored as Language) || 'zh';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('preferred-language', lang);
    // Set document direction for RTL languages
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  };

  useEffect(() => {
    // Set initial direction
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
