import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'hi' | 'fr' | 'ar' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.none': 'None',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.type': 'Type',
    'common.note': 'Note',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.add': 'Add',
    'common.update': 'Update',
    'common.getStarted': 'Get started',
    'common.refresh': 'Refresh',
    'common.dataDelayed': 'Data delayed',
    
    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.logOut': 'Log Out',
    'auth.register': 'Register',
    'auth.signUp': 'Sign up',
    'auth.signIn': 'Sign In',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.username': 'Username',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.createAccount': 'Create Account',
    'auth.enterCredentials': 'Enter your credentials to access your account',
    'auth.fillDetails': 'Fill in your details to get started',
    'auth.loggingIn': 'Logging in...',
    'auth.registering': 'Registering...',
    'auth.backToHome': '← Back to Home',
    'auth.welcomeBack': 'Welcome Back to MetaMask Trade',
    'auth.startJourney': 'Start Your Investment Journey',
    'auth.accessPortfolio': 'Access your portfolio and continue trading with the most secure platform.',
    'auth.completeRegistration': 'Complete your registration and unlock the gateway to exciting investment opportunities.',
    'auth.connectWallet': 'Connect Wallet',
    'auth.openMetaMask': 'Open in MetaMask',
    'auth.orContinueEmail': 'Or continue with email',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.chooseUsername': 'Choose a username',
    'auth.createPassword': 'Create a password (min 6 chars)',
    'auth.confirmYourPassword': 'Confirm your password',
    'auth.signOutAccount': 'Sign out of your account',
    
    // Navigation
    'nav.home': 'Home',
    'nav.market': 'Market',
    'nav.trade': 'Trade',
    'nav.smartTrading': 'Smart Trading',
    'nav.loan': 'Loan',
    'nav.account': 'Account',
    'nav.admin': 'Admin',
    'nav.adminPanel': 'Admin Panel',
    'nav.customerService': 'Customer Service',
    'nav.backToMarket': 'Back to Market',
    
    // Hero Section
    'hero.title': 'Buy, trade, and hold 350+ cryptocurrencies on MetaMask Trade',
    'hero.appStore': 'App Store',
    'hero.application': 'Application',
    'hero.appDescription': 'Mobile banking that throws out the role book and gives you a precision tool for managing your finances.',
    'hero.cryptoDeposit': 'Crypto deposit',
    'hero.cryptoDescription': 'By using cryptocurrency for deposit, an additional layer of security is obtained.',
    
    // Stats Section
    'stats.tradingVolume': '24h trading volume',
    'stats.cryptocurrencies': 'Cryptocurrencies',
    'stats.registeredUsers': 'Registered users',
    
    // Features Section
    'features.lowestFees': 'Lowest transactions fees < 0.3%',
    'features.tradeAllCrypto': 'Trade all crypto in one place',
    'features.cryptoList': 'BTC, ETH, SOL, XRP, and 350+ cryptocurrencies',
    'features.interestFree': '7 days interest-free',
    'features.cryptoLoans': 'Cryptocurrency loans',
    'features.loanDescription': 'Borrow crypto with low interest. Max 15 days loan period.',
    'features.simpleStable': 'Simple and stable',
    'features.smartTrading': 'Smart trading',
    'features.smartTradingDesc': 'One click to create your earning plan',
    
    // Feature badges
    'feature.bankSecurity': 'Bank-Level Security',
    'feature.bankSecurityDesc': '256-bit encryption for all transactions',
    'feature.realTimeTrading': 'Real-Time Trading',
    'feature.realTimeTradingDesc': 'Trade 350+ cryptocurrencies instantly',
    'feature.selfCustody': 'Self-Custody',
    'feature.selfCustodyDesc': 'You control your private keys',
    'feature.secureAndTrusted': 'Secure & Trusted',
    
    // Market Page
    'market.title': 'Cryptocurrency Prices by Market Cap',
    'market.description': 'The global cryptocurrency market cap today is',
    'market.with24hVolume': 'with a 24-hour trading volume of',
    'market.searchPlaceholder': 'Search cryptocurrency...',
    'market.totalCoins': 'Total Coins',
    'market.activeMarkets': 'Active Markets',
    'market.btcDominance': 'BTC Dominance',
    'market.ethDominance': 'ETH Dominance',
    'market.coin': 'Coin',
    'market.price': 'Price',
    'market.change24h': '24h %',
    'market.marketCap': 'Market Cap',
    'market.volume24h': 'Volume (24h)',
    'market.loadingData': 'Loading market data...',
    'market.noResults': 'No results found for',
    'market.noData': 'No market data available',
    'market.dataUpdates': 'Data updates every 15 seconds via CoinGecko API',
    
    // Trade Page
    'trade.chart': 'Chart',
    'trade.buy': 'Buy',
    'trade.sell': 'Sell',
    'trade.orderType': 'Order Type',
    'trade.marketOrder': 'Market Order',
    'trade.limitOrder': 'Limit Order',
    'trade.quantity': 'Quantity',
    'trade.total': 'Total',
    'trade.placeOrder': 'Place Order',
    
    // Loan Page
    'loan.title': 'Cryptocurrency Loans',
    'loan.description': 'Borrow {min} - {max} USDT with 7 days interest-free!',
    'loan.terms': 'Loan Terms',
    'loan.amountLimit': 'Amount Limit',
    'loan.days1to7': 'Days 1-7',
    'loan.interestFreePeriod': 'Interest-free period',
    'loan.days8to15': 'Days 8-15',
    'loan.dailyInterest': '1% daily interest',
    'loan.afterDay15': 'After Day 15',
    'loan.dailyPenalty': '2% daily penalty',
    'loan.withdrawalLock': 'Withdrawal Lock',
    'loan.cannotWithdraw': 'Cannot withdraw with active loan',
    'loan.apply': 'Apply',
    'loan.repayment': 'Repayment',
    'loan.history': 'History',
    'loan.active': 'Active Loans',
    'loan.pending': 'Pending Approval',
    'loan.noLoan': 'No Loan',
    'loan.owed': 'Owed',

    // Loan - Application
    'loan.applyTitle': 'Apply for Loan',
    'loan.accountFrozen': 'Account Frozen',
    'loan.accountFrozenDesc': 'Your account has been frozen. Loan applications are disabled. Please contact customer support.',
    'loan.kycRequired': 'Identity Verification Required',
    'loan.kycRequiredDesc': 'Please complete identity verification before applying for a loan.',
    'loan.goToVerification': 'Go to Verification →',
    'loan.selectCurrency': 'Select Currency',
    'loan.loanAmount': 'Loan Amount',
    'loan.guarantorOptional': 'Guarantor (Optional)',
    'loan.guarantorHint': 'Adding a guarantor can increase the loan amount and the success rate.',
    'loan.guarantorName': 'Guarantor name',
    'loan.guarantorContact': 'Guarantor contact (phone/email)',
    'loan.minLabel': 'Min',
    'loan.maxLabel': 'Max',
    'loan.interestFreeInfo': 'Interest-free period: 7 days',
    'loan.after7DaysInterestInfo': 'After 7 days: 1% daily interest',
    'loan.after15DaysPenaltyInfo': 'After 15 days: 2% daily penalty',
    'loan.activeLoansNotice': 'You have {count} active loan(s). Max 3 allowed.',
    'loan.submitting': 'Submitting...',

    // Loan - Repayment
    'loan.repaymentTitle': 'Loan Repayment',
    'loan.hideHistory': 'Hide History',
    'loan.showHistory': 'Show History',
    'loan.totalRemainingBalance': 'Total Remaining Balance',
    'loan.outstandingLoans': 'Outstanding Loans',
    'loan.paidOffLoans': 'Paid Off Loans',
    'loan.repayNow': 'Repay Now',
    'loan.repaymentInfo1': 'Click "Repay Now" to submit a repayment request',
    'loan.repaymentInfo2': '• Payment priority: Penalty → Interest → Principal',
    'loan.repaymentInfo3': '• Early repayment supported, no interest for first 7 days',
    'loan.repaymentHistoryTitle': 'Repayment History',
    'loan.records': 'records',
    'loan.noRepaymentRecords': 'No repayment records',
    'loan.noLoansFound': 'No loans found',
    'loan.goToApplyHint': 'Go to the loan application page to apply for a loan',
    'loan.principal': 'Principal',
    'loan.interest': 'Interest',
    'loan.penalty': 'Penalty',
    'loan.totalOwed': 'Total Owed',
    'loan.repaymentType': 'Repayment Type',
    'loan.partialRepayment': 'Partial Repayment',
    'loan.earlyFullRepayment': 'Early Full Repayment',
    'loan.fullRepaymentOnDue': 'Full Repayment (On Due Date)',
    'loan.submitRepaymentRequest': 'Submit Repayment Request',
    'loan.rejectedReason': 'Rejection reason',

    // Loan - History
    'loan.historyTitle': 'Loan History',
    'loan.noLoanHistoryYet': 'No loan history yet',
    'loan.loansAppearHere': 'Your loans will appear here',
    'loan.totalCount': '{count} total',
    'loan.applicationDate': 'Application Date',
    'loan.repaidDate': 'Repaid Date',
    'loan.currentOwed': 'Current Owed',
    'loan.fullyPaid': 'Fully Paid',
    'loan.statusPending': 'Pending',
    'loan.statusActive': 'Active',
    'loan.statusOverdue': 'Overdue',
    'loan.statusRepaid': 'Repaid',
    'loan.statusRejected': 'Rejected',

    // Validation / Toasts
    'loan.enterValidAmount': 'Please enter a valid amount',
    'loan.minimumLoanAmountIs': 'Minimum loan amount is {amount} {currency}',
    'loan.maximumLoanAmountIs': 'Maximum loan amount is {amount} {currency}',
    'loan.maxActiveLoans': 'Maximum 3 active loans allowed',
    'loan.applicationSubmitted': 'Loan application submitted for {amount} {currency}. Waiting for approval.',
    'loan.applicationFailed': 'Failed to process loan application',
    'loan.repaymentSubmitted': 'Repayment request submitted, awaiting admin review',
    'loan.amountCannotExceedTotal': 'Amount cannot exceed the total owed',
    'loan.submissionFailedTryAgain': 'Submission failed, please try again',
    'loan.imageTooLarge': 'Image size must be less than 5MB',
    'loan.receiptAlt': 'Receipt',
    'loan.repaymentAmount': 'Repayment Amount',
    'loan.enterRepaymentAmount': 'Enter repayment amount',
    'loan.paymentReceipt': 'Payment Receipt (Optional)',
    'loan.uploadPaymentReceipt': 'Upload payment receipt',
    'loan.uploadLimit': 'Max 5MB, JPG/PNG supported',
    'loan.awaitingAdminReview': 'Awaiting admin review after submission',
    'loan.earlyRepaymentReduceInterest': 'Early repayment can reduce interest',
    'loan.confirmSubmit': 'Confirm Submit',


    // Account Page
    'account.totalAssets': 'Account Total Assets',
    'account.floatingPnL': 'Floating P&L',
    'account.balance': 'Balance',
    'account.loan': 'Loan',
    'account.withdraw': 'Withdraw',
    'account.recharge': 'Recharge',
    'account.exchange': 'Exchange',
    'account.verify': 'Verify',
    'account.cryptoAssets': 'Crypto Assets',
    'account.myAssets': 'My Assets',
    'account.totalBalance': 'Total Balance',
    'account.deposit': 'Deposit',
    'account.transfer': 'Transfer',
    'account.tradeHistory': 'Trade History',
    'account.settings': 'Settings',
    'account.security': 'Security',
    'account.verification': 'Identity Verification',
    'account.withdrawAmount': 'Withdraw Amount',
    'account.receivingAddress': 'Receiving Address',
    'account.network': 'Network',
    'account.fee': 'Fee',
    'account.youWillReceive': 'You will receive',
    'account.minimumWithdraw': 'Minimum withdrawal',
    'account.submitWithdraw': 'Submit Withdrawal',
    'account.rechargeAmount': 'Recharge Amount',
    'account.uploadReceipt': 'Upload Receipt',
    'account.copyAddress': 'Copy Address',
    'account.scanQR': 'Scan QR code to deposit',
    'account.withdrawHistory': 'Withdrawal History',
    'account.pending': 'Pending',
    'account.completed': 'Completed',
    'account.failed': 'Failed',
    'account.frozenAccount': 'Account Frozen',
    'account.frozenMessage': 'Your account has been frozen. Please contact customer service.',
    'account.activeLoanMessage': 'You have an active loan. Please repay before withdrawing.',
    
    // KYC
    'kyc.title': 'Identity Verification',
    'kyc.subtitle': 'Complete KYC to unlock all features',
    'kyc.fullName': 'Full Name',
    'kyc.idNumber': 'ID Number',
    'kyc.idType': 'ID Type',
    'kyc.passport': 'Passport',
    'kyc.driverLicense': 'Driver License',
    'kyc.nationalId': 'National ID',
    'kyc.other': 'Other',
    'kyc.uploadId': 'Upload ID Document',
    'kyc.uploadSelfie': 'Upload Selfie',
    'kyc.submit': 'Submit Verification',
    'kyc.approved': 'Verified',
    'kyc.pending': 'Pending Review',
    'kyc.rejected': 'Rejected',
    'kyc.notSubmitted': 'Not Submitted',
    'kyc.verificationComplete': 'Verification Complete',
    'kyc.verificationPending': 'Verification Pending',
    
    // Account Status
    'status.normal': 'Normal',
    'status.frozen': 'Frozen',
    
    // Footer
    'footer.language': 'Language',
    'footer.description': 'The world\'s leading cryptocurrency exchange platform. Trade securely with the lowest fees and fastest execution.',
    'footer.products': 'Products',
    'footer.spotTrading': 'Spot Trading',
    'footer.marginTrading': 'Margin Trading',
    'footer.derivatives': 'Derivatives',
    'footer.loans': 'Loans',
    'footer.services': 'Services',
    'footer.copyTrading': 'Copy Trading',
    'footer.api': 'API',
    'footer.mobileApp': 'Mobile App',
    'footer.support': 'Support',
    'footer.helpCenter': 'Help Center',
    'footer.contactUs': 'Contact Us',
    'footer.faq': 'FAQ',
    'footer.fees': 'Fees',
    'footer.legal': 'Legal',
    'footer.allRightsReserved': 'All rights reserved.',
    
    // Admin
    'admin.userManagement': 'User Management',
    'admin.username': 'Username',
    'admin.email': 'Email',
    'admin.balance': 'Balance',
    'admin.loanStatus': 'Loan Status',
    'admin.kyc': 'KYC',
    'admin.registerDate': 'Register Date',
    'admin.modifyBalance': 'Modify Balance',
    'admin.fundDetails': 'Fund Details',
    'admin.freezeAccount': 'Freeze Account',
    'admin.unfreezeAccount': 'Unfreeze Account',
    'admin.userDetails': 'User Details',
    'admin.loginIP': 'Login IP',
    'admin.lastLogin': 'Last Login',
    'admin.kycHistory': 'KYC History',
    'admin.viewDetails': 'View Details',
    'admin.noKYC': 'No KYC Record',
    'admin.kycPhotos': 'KYC Photos',
    'admin.frontImage': 'ID Front',
    'admin.backImage': 'ID Back',
    'admin.selfie': 'Selfie',
    'admin.changePassword': 'Change Password',
    'admin.newPassword': 'New Password',
    'admin.confirmNewPassword': 'Confirm New Password',
    'admin.passwordMinLength': 'Password must be at least 6 characters',
    'admin.passwordMismatch': 'Passwords do not match',
  },
  zh: {
    // Common
    'common.loading': '加载中...',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.close': '关闭',
    'common.submit': '提交',
    'common.success': '成功',
    'common.error': '错误',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.all': '全部',
    'common.none': '无',
    'common.status': '状态',
    'common.actions': '操作',
    'common.date': '日期',
    'common.amount': '金额',
    'common.type': '类型',
    'common.note': '备注',
    'common.back': '返回',
    'common.next': '下一步',
    'common.previous': '上一步',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.view': '查看',
    'common.add': '添加',
    'common.update': '更新',
    'common.getStarted': '开始使用',
    'common.refresh': '刷新',
    'common.dataDelayed': '数据延迟',
    
    // Auth
    'auth.login': '登录',
    'auth.logout': '退出登录',
    'auth.logOut': '退出登录',
    'auth.register': '注册',
    'auth.signUp': '注册',
    'auth.signIn': '登录',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.username': '用户名',
    'auth.forgotPassword': '忘记密码？',
    'auth.noAccount': '还没有账户？',
    'auth.hasAccount': '已有账户？',
    'auth.createAccount': '创建账户',
    'auth.enterCredentials': '输入您的凭据以访问您的账户',
    'auth.fillDetails': '填写您的详细信息以开始',
    'auth.loggingIn': '登录中...',
    'auth.registering': '注册中...',
    'auth.backToHome': '← 返回首页',
    'auth.welcomeBack': '欢迎回到 MetaMask Trade',
    'auth.startJourney': '开启您的投资之旅',
    'auth.accessPortfolio': '访问您的投资组合，使用最安全的平台继续交易。',
    'auth.completeRegistration': '完成注册，开启激动人心的投资机会。',
    'auth.connectWallet': '连接钱包',
    'auth.openMetaMask': '在 MetaMask 中打开',
    'auth.orContinueEmail': '或使用邮箱继续',
    'auth.enterEmail': '输入您的邮箱',
    'auth.enterPassword': '输入您的密码',
    'auth.chooseUsername': '选择用户名',
    'auth.createPassword': '创建密码（至少6位）',
    'auth.confirmYourPassword': '确认您的密码',
    'auth.signOutAccount': '退出您的账户',
    
    // Navigation
    'nav.home': '首页',
    'nav.market': '行情',
    'nav.trade': '交易',
    'nav.smartTrading': '智能交易',
    'nav.loan': '贷款',
    'nav.account': '账户',
    'nav.admin': '管理',
    'nav.adminPanel': '管理面板',
    'nav.customerService': '客服',
    'nav.backToMarket': '返回市场',
    
    // Hero Section
    'hero.title': '在 MetaMask Trade 购买、交易和持有 350+ 种加密货币',
    'hero.appStore': 'App Store',
    'hero.application': '应用程序',
    'hero.appDescription': '移动银行打破常规，为您提供精确的财务管理工具。',
    'hero.cryptoDeposit': '加密货币充值',
    'hero.cryptoDescription': '使用加密货币充值，获得额外的安全保障。',
    
    // Stats Section
    'stats.tradingVolume': '24小时交易量',
    'stats.cryptocurrencies': '加密货币种类',
    'stats.registeredUsers': '注册用户',
    
    // Features Section
    'features.lowestFees': '最低交易费用 < 0.3%',
    'features.tradeAllCrypto': '一站式交易所有加密货币',
    'features.cryptoList': 'BTC, ETH, SOL, XRP 及 350+ 种加密货币',
    'features.interestFree': '7天免息',
    'features.cryptoLoans': '加密货币贷款',
    'features.loanDescription': '低息借贷加密货币，最长15天贷款期限。',
    'features.simpleStable': '简单稳定',
    'features.smartTrading': '智能交易',
    'features.smartTradingDesc': '一键创建您的收益计划',
    
    // Feature badges
    'feature.bankSecurity': '银行级安全',
    'feature.bankSecurityDesc': '所有交易采用256位加密',
    'feature.realTimeTrading': '实时交易',
    'feature.realTimeTradingDesc': '即时交易350+种加密货币',
    'feature.selfCustody': '自托管',
    'feature.selfCustodyDesc': '您控制自己的私钥',
    'feature.secureAndTrusted': '安全可信',
    
    // Market Page
    'market.title': '按市值排名的加密货币价格',
    'market.description': '全球加密货币市值今日为',
    'market.with24hVolume': '24小时交易量为',
    'market.searchPlaceholder': '搜索加密货币...',
    'market.totalCoins': '币种总数',
    'market.activeMarkets': '活跃市场',
    'market.btcDominance': 'BTC 占比',
    'market.ethDominance': 'ETH 占比',
    'market.coin': '币种',
    'market.price': '价格',
    'market.change24h': '24小时涨跌',
    'market.marketCap': '市值',
    'market.volume24h': '24小时成交量',
    'market.loadingData': '正在加载市场数据...',
    'market.noResults': '未找到相关结果',
    'market.noData': '暂无市场数据',
    'market.dataUpdates': '数据每15秒通过CoinGecko API更新',
    
    // Trade Page
    'trade.chart': '图表',
    'trade.buy': '买入',
    'trade.sell': '卖出',
    'trade.orderType': '订单类型',
    'trade.marketOrder': '市价单',
    'trade.limitOrder': '限价单',
    'trade.quantity': '数量',
    'trade.total': '总计',
    'trade.placeOrder': '下单',
    
    // Loan Page
    'loan.title': '加密货币贷款',
    'loan.description': '借款 {min} - {max} USDT，享7天免息！',
    'loan.terms': '贷款条款',
    'loan.amountLimit': '借款额度',
    'loan.days1to7': '第1-7天',
    'loan.interestFreePeriod': '免息期',
    'loan.days8to15': '第8-15天',
    'loan.dailyInterest': '每日1%利息',
    'loan.afterDay15': '第15天后',
    'loan.dailyPenalty': '每日2%罚息',
    'loan.withdrawalLock': '提现锁定',
    'loan.cannotWithdraw': '有贷款时无法提现',
    'loan.apply': '申请',
    'loan.repayment': '还款',
    'loan.history': '历史',
    'loan.active': '笔进行中',
    'loan.pending': '待审批',
    'loan.noLoan': '无贷款',
    'loan.owed': '欠款',

    // Loan - Application
    'loan.applyTitle': '贷款申请',
    'loan.accountFrozen': '账户已冻结',
    'loan.accountFrozenDesc': '您的账户已被冻结，暂无法申请贷款。请联系客服处理。',
    'loan.kycRequired': '需要身份认证',
    'loan.kycRequiredDesc': '申请贷款前请先完成身份认证。',
    'loan.goToVerification': '前往认证 →',
    'loan.selectCurrency': '选择币种',
    'loan.loanAmount': '贷款金额',
    'loan.guarantorOptional': '担保人（可选）',
    'loan.guarantorHint': '添加担保人可提升额度与通过率。',
    'loan.guarantorName': '担保人姓名',
    'loan.guarantorContact': '担保人联系方式（电话/邮箱）',
    'loan.minLabel': '最小',
    'loan.maxLabel': '最大',
    'loan.interestFreeInfo': '免息期：7天',
    'loan.after7DaysInterestInfo': '超过7天：每日1%利息',
    'loan.after15DaysPenaltyInfo': '超过15天：每日2%罚息',
    'loan.activeLoansNotice': '您当前有 {count} 笔进行中贷款，最多可同时拥有3笔。',
    'loan.submitting': '提交中...',

    // Loan - Repayment
    'loan.repaymentTitle': '贷款还款',
    'loan.hideHistory': '隐藏记录',
    'loan.showHistory': '显示记录',
    'loan.totalRemainingBalance': '剩余应还总额',
    'loan.outstandingLoans': '未结清贷款',
    'loan.paidOffLoans': '已结清贷款',
    'loan.repayNow': '立即还款',
    'loan.repaymentInfo1': '点击“立即还款”提交还款申请',
    'loan.repaymentInfo2': '• 扣款顺序：罚息 → 利息 → 本金',
    'loan.repaymentInfo3': '• 支持提前结清，前7天免息',
    'loan.repaymentHistoryTitle': '还款记录',
    'loan.records': '条',
    'loan.noRepaymentRecords': '暂无还款记录',
    'loan.noLoansFound': '暂无贷款',
    'loan.goToApplyHint': '前往“申请”页面发起贷款申请',
    'loan.principal': '本金',
    'loan.interest': '利息',
    'loan.penalty': '罚息',
    'loan.totalOwed': '应还总额',
    'loan.repaymentType': '还款类型',
    'loan.partialRepayment': '部分还款',
    'loan.earlyFullRepayment': '提前结清',
    'loan.fullRepaymentOnDue': '到期全额还款',
    'loan.submitRepaymentRequest': '提交还款申请',
    'loan.rejectedReason': '驳回原因',

    // Loan - History
    'loan.historyTitle': '贷款历史',
    'loan.noLoanHistoryYet': '暂无贷款记录',
    'loan.loansAppearHere': '您的贷款记录会显示在这里',
    'loan.totalCount': '共 {count} 笔',
    'loan.applicationDate': '申请日期',
    'loan.repaidDate': '结清日期',
    'loan.currentOwed': '当前应还',
    'loan.fullyPaid': '已结清',
    'loan.statusPending': '待审批',
    'loan.statusActive': '进行中',
    'loan.statusOverdue': '已逾期',
    'loan.statusRepaid': '已结清',
    'loan.statusRejected': '已拒绝',

    // Validation / Toasts
    'loan.enterValidAmount': '请输入有效金额',
    'loan.minimumLoanAmountIs': '最低贷款金额为 {amount} {currency}',
    'loan.maximumLoanAmountIs': '最高贷款金额为 {amount} {currency}',
    'loan.maxActiveLoans': '最多同时拥有3笔进行中贷款',
    'loan.applicationSubmitted': '已提交 {amount} {currency} 的贷款申请，等待审批。',
    'loan.applicationFailed': '贷款申请处理失败',
    'loan.repaymentSubmitted': '还款申请已提交，等待管理员审核',
    'loan.amountCannotExceedTotal': '还款金额不能超过应还总额',
    'loan.submissionFailedTryAgain': '提交失败，请重试',
    'loan.imageTooLarge': '图片大小需小于 5MB',
    'loan.receiptAlt': '回执',
    'loan.repaymentAmount': '还款金额',
    'loan.enterRepaymentAmount': '请输入还款金额',
    'loan.paymentReceipt': '付款凭证（可选）',
    'loan.uploadPaymentReceipt': '上传付款凭证',
    'loan.uploadLimit': '最大 5MB，支持 JPG/PNG',
    'loan.awaitingAdminReview': '提交后等待管理员审核',
    'loan.earlyRepaymentReduceInterest': '提前还款可减少利息',
    'loan.confirmSubmit': '确认提交',

    // Account Page
    'account.totalAssets': '账户总资产',
    'account.floatingPnL': '浮动盈亏',
    'account.balance': '余额',
    'account.loan': '贷款',
    'account.withdraw': '提现',
    'account.recharge': '充值',
    'account.exchange': '兑换',
    'account.verify': '认证',
    'account.cryptoAssets': '加密资产',
    'account.myAssets': '我的资产',
    'account.totalBalance': '总余额',
    'account.deposit': '充值',
    'account.transfer': '转账',
    'account.tradeHistory': '交易历史',
    'account.settings': '设置',
    'account.security': '安全',
    'account.verification': '身份验证',
    'account.withdrawAmount': '提现金额',
    'account.receivingAddress': '收款地址',
    'account.network': '网络',
    'account.fee': '手续费',
    'account.youWillReceive': '实际到账',
    'account.minimumWithdraw': '最低提现',
    'account.submitWithdraw': '提交提现',
    'account.rechargeAmount': '充值金额',
    'account.uploadReceipt': '上传凭证',
    'account.copyAddress': '复制地址',
    'account.scanQR': '扫描二维码充值',
    'account.withdrawHistory': '提现记录',
    'account.pending': '处理中',
    'account.completed': '已完成',
    'account.failed': '失败',
    'account.frozenAccount': '账户已冻结',
    'account.frozenMessage': '您的账户已被冻结，请联系客服。',
    'account.activeLoanMessage': '您有未还清的贷款，请先还款后再提现。',
    
    // KYC
    'kyc.title': '身份验证',
    'kyc.subtitle': '完成KYC以解锁所有功能',
    'kyc.fullName': '真实姓名',
    'kyc.idNumber': '证件号码',
    'kyc.idType': '证件类型',
    'kyc.passport': '护照',
    'kyc.driverLicense': '驾驶证',
    'kyc.nationalId': '身份证',
    'kyc.other': '其他',
    'kyc.uploadId': '上传证件照片',
    'kyc.uploadSelfie': '上传自拍照',
    'kyc.submit': '提交认证',
    'kyc.approved': '已认证',
    'kyc.pending': '待审核',
    'kyc.rejected': '已拒绝',
    'kyc.notSubmitted': '未提交',
    'kyc.verificationComplete': '认证完成',
    'kyc.verificationPending': '认证审核中',
    
    // Account Status
    'status.normal': '正常',
    'status.frozen': '已冻结',
    
    // Footer
    'footer.language': '语言',
    'footer.description': '全球领先的加密货币交易平台。以最低的费用和最快的执行速度安全交易。',
    'footer.products': '产品',
    'footer.spotTrading': '现货交易',
    'footer.marginTrading': '保证金交易',
    'footer.derivatives': '衍生品',
    'footer.loans': '贷款',
    'footer.services': '服务',
    'footer.copyTrading': '跟单交易',
    'footer.api': 'API',
    'footer.mobileApp': '移动应用',
    'footer.support': '支持',
    'footer.helpCenter': '帮助中心',
    'footer.contactUs': '联系我们',
    'footer.faq': '常见问题',
    'footer.fees': '费率',
    'footer.legal': '法律',
    'footer.allRightsReserved': '版权所有。',
    
    // Admin
    'admin.userManagement': '用户管理',
    'admin.username': '用户名',
    'admin.email': '邮箱',
    'admin.balance': '余额',
    'admin.loanStatus': '贷款情况',
    'admin.kyc': '实名认证',
    'admin.registerDate': '注册时间',
    'admin.modifyBalance': '修改余额',
    'admin.fundDetails': '资金明细',
    'admin.freezeAccount': '冻结账户',
    'admin.unfreezeAccount': '解冻账户',
    'admin.userDetails': '用户详情',
    'admin.loginIP': '登录IP',
    'admin.lastLogin': '最后登录',
    'admin.kycHistory': 'KYC历史记录',
    'admin.viewDetails': '查看详情',
    'admin.noKYC': '暂无KYC记录',
    'admin.kycPhotos': 'KYC照片',
    'admin.frontImage': '证件正面',
    'admin.backImage': '证件背面',
    'admin.selfie': '自拍照',
    'admin.changePassword': '修改密码',
    'admin.newPassword': '新密码',
    'admin.confirmNewPassword': '确认新密码',
    'admin.passwordMinLength': '密码至少需要6个字符',
    'admin.passwordMismatch': '两次密码不一致',
  },
  es: {
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.close': 'Cerrar',
    'common.submit': 'Enviar',
    'common.getStarted': 'Comenzar',
    'common.refresh': 'Actualizar',
    'common.dataDelayed': 'Datos retrasados',
    'auth.login': 'Iniciar sesión',
    'auth.logout': 'Cerrar sesión',
    'auth.logOut': 'Cerrar sesión',
    'auth.signUp': 'Registrarse',
    'auth.connectWallet': 'Conectar billetera',
    'auth.signOutAccount': 'Cerrar sesión de tu cuenta',
    'nav.home': 'Inicio',
    'nav.market': 'Mercado',
    'nav.trade': 'Comercio',
    'nav.smartTrading': 'Trading Inteligente',
    'nav.loan': 'Préstamo',
    'nav.account': 'Cuenta',
    'nav.admin': 'Admin',
    'nav.customerService': 'Atención al cliente',
    'nav.backToMarket': 'Volver al mercado',
    'hero.title': 'Compra, intercambia y mantén más de 350 criptomonedas en MetaMask Trade',
    'hero.appStore': 'App Store',
    'hero.application': 'Aplicación',
    'hero.appDescription': 'Banca móvil que rompe las reglas y te da una herramienta precisa.',
    'hero.cryptoDeposit': 'Depósito cripto',
    'hero.cryptoDescription': 'Seguridad adicional con depósitos en criptomonedas.',
    'stats.tradingVolume': 'Volumen 24h',
    'stats.cryptocurrencies': 'Criptomonedas',
    'stats.registeredUsers': 'Usuarios registrados',
    'features.lowestFees': 'Comisiones más bajas < 0.3%',
    'features.tradeAllCrypto': 'Opera todas las cripto en un solo lugar',
    'features.cryptoList': 'BTC, ETH, SOL, XRP y más de 350 criptomonedas',
    'features.interestFree': '7 días sin intereses',
    'features.cryptoLoans': 'Préstamos de criptomonedas',
    'features.loanDescription': 'Préstamos cripto con bajo interés. Máximo 15 días.',
    'features.simpleStable': 'Simple y estable',
    'features.smartTrading': 'Trading inteligente',
    'features.smartTradingDesc': 'Un clic para crear tu plan de ganancias',
    'market.title': 'Precios de criptomonedas por capitalización',
    'market.searchPlaceholder': 'Buscar criptomoneda...',
    'market.totalCoins': 'Total monedas',
    'market.activeMarkets': 'Mercados activos',
    'market.coin': 'Moneda',
    'market.price': 'Precio',
    'market.loadingData': 'Cargando datos del mercado...',
    'loan.title': 'Préstamos de criptomonedas',
    'loan.terms': 'Términos del préstamo',
    'loan.apply': 'Solicitar',
    'loan.repayment': 'Pago',
    'loan.history': 'Historial',
    'account.totalAssets': 'Activos totales',
    'account.balance': 'Saldo',
    'account.loan': 'Préstamo',
    'account.withdraw': 'Retirar',
    'account.recharge': 'Recargar',
    'account.exchange': 'Intercambiar',
    'account.verify': 'Verificar',
    'account.cryptoAssets': 'Activos cripto',
    'footer.language': 'Idioma',
    'footer.products': 'Productos',
    'footer.services': 'Servicios',
    'footer.support': 'Soporte',
    'footer.legal': 'Legal',
    'footer.allRightsReserved': 'Todos los derechos reservados.',
  },
  hi: {
    'common.loading': 'लोड हो रहा है...',
    'common.getStarted': 'शुरू करें',
    'common.refresh': 'रीफ्रेश',
    'auth.login': 'लॉगिन',
    'auth.logout': 'लॉगआउट',
    'auth.logOut': 'लॉग आउट',
    'auth.signUp': 'साइन अप',
    'auth.connectWallet': 'वॉलेट कनेक्ट करें',
    'nav.home': 'होम',
    'nav.market': 'बाज़ार',
    'nav.trade': 'व्यापार',
    'nav.smartTrading': 'स्मार्ट ट्रेडिंग',
    'nav.loan': 'ऋण',
    'nav.account': 'खाता',
    'nav.customerService': 'ग्राहक सेवा',
    'hero.title': 'MetaMask Trade पर 350+ क्रिप्टोकरेंसी खरीदें, ट्रेड करें और होल्ड करें',
    'stats.tradingVolume': '24 घंटे ट्रेडिंग वॉल्यूम',
    'stats.cryptocurrencies': 'क्रिप्टोकरेंसी',
    'stats.registeredUsers': 'पंजीकृत उपयोगकर्ता',
    'market.title': 'मार्केट कैप के अनुसार क्रिप्टोकरेंसी कीमतें',
    'market.searchPlaceholder': 'क्रिप्टोकरेंसी खोजें...',
    'loan.title': 'क्रिप्टोकरेंसी ऋण',
    'account.totalAssets': 'कुल संपत्ति',
    'account.balance': 'शेष राशि',
    'account.withdraw': 'निकासी',
    'account.recharge': 'रिचार्ज',
    'account.exchange': 'विनिमय',
    'account.verify': 'सत्यापित करें',
    'footer.language': 'भाषा',
  },
  fr: {
    'common.loading': 'Chargement...',
    'common.getStarted': 'Commencer',
    'common.refresh': 'Actualiser',
    'auth.login': 'Connexion',
    'auth.logout': 'Déconnexion',
    'auth.logOut': 'Se déconnecter',
    'auth.signUp': "S'inscrire",
    'auth.connectWallet': 'Connecter le portefeuille',
    'nav.home': 'Accueil',
    'nav.market': 'Marché',
    'nav.trade': 'Commerce',
    'nav.smartTrading': 'Trading Intelligent',
    'nav.loan': 'Prêt',
    'nav.account': 'Compte',
    'nav.customerService': 'Service client',
    'hero.title': 'Achetez, échangez et conservez plus de 350 cryptomonnaies sur MetaMask Trade',
    'stats.tradingVolume': 'Volume 24h',
    'stats.cryptocurrencies': 'Cryptomonnaies',
    'stats.registeredUsers': 'Utilisateurs inscrits',
    'market.title': 'Prix des cryptomonnaies par capitalisation',
    'market.searchPlaceholder': 'Rechercher une cryptomonnaie...',
    'loan.title': 'Prêts de cryptomonnaies',
    'account.totalAssets': 'Actifs totaux',
    'account.balance': 'Solde',
    'account.withdraw': 'Retirer',
    'account.recharge': 'Recharger',
    'account.exchange': 'Échanger',
    'account.verify': 'Vérifier',
    'footer.language': 'Langue',
  },
  ar: {
    'common.loading': 'جاري التحميل...',
    'common.getStarted': 'ابدأ الآن',
    'common.refresh': 'تحديث',
    'auth.login': 'تسجيل الدخول',
    'auth.logout': 'تسجيل الخروج',
    'auth.logOut': 'تسجيل الخروج',
    'auth.signUp': 'التسجيل',
    'auth.connectWallet': 'ربط المحفظة',
    'nav.home': 'الرئيسية',
    'nav.market': 'السوق',
    'nav.trade': 'التداول',
    'nav.smartTrading': 'التداول الذكي',
    'nav.loan': 'القرض',
    'nav.account': 'الحساب',
    'nav.customerService': 'خدمة العملاء',
    'hero.title': 'اشترِ وتداول واحتفظ بأكثر من 350 عملة مشفرة على MetaMask Trade',
    'stats.tradingVolume': 'حجم التداول 24 ساعة',
    'stats.cryptocurrencies': 'العملات المشفرة',
    'stats.registeredUsers': 'المستخدمين المسجلين',
    'market.title': 'أسعار العملات المشفرة حسب القيمة السوقية',
    'market.searchPlaceholder': 'البحث عن عملة مشفرة...',
    'loan.title': 'قروض العملات المشفرة',
    'account.totalAssets': 'إجمالي الأصول',
    'account.balance': 'الرصيد',
    'account.withdraw': 'سحب',
    'account.recharge': 'إيداع',
    'account.exchange': 'تبادل',
    'account.verify': 'التحقق',
    'footer.language': 'اللغة',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('preferred-language');
    return (stored as Language) || 'zh';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('preferred-language', lang);
    // Set document direction for RTL languages
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  };

  useEffect(() => {
    // Set initial direction
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
